In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import torch

***Reshaping Tensor***

In [2]:
a = torch.ones(4,4)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [3]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [4]:
#Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
b= torch.rand(2,3,4)
print(b)

tensor([[[0.1170, 0.2774, 0.5664, 0.0485],
         [0.1552, 0.8170, 0.6408, 0.7531],
         [0.8339, 0.6310, 0.2046, 0.3362]],

        [[0.5544, 0.0423, 0.1911, 0.4818],
         [0.0427, 0.4034, 0.5934, 0.8845],
         [0.2500, 0.0777, 0.1270, 0.4440]]])


In [7]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [9]:
#conversion of Tensor in numpy

import numpy as np

a = torch.tensor([1,2,3,4])
b = a.numpy()
print(b)

[1 2 3 4]


In [11]:
type(b)


numpy.ndarray

In [13]:
#from numpy array to tensor

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
torch.from_numpy(a)

tensor([1, 2, 3, 4])