In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch
print(torch.__version__)

2.5.1+cu121


In [3]:
# Check if GPU is available
if torch.cuda.is_available():
    print("GPU is available.")
    print("GPU Name:", torch.cuda.get_device_name(0))
else:
    print("GPU is not available.")


GPU is available.
GPU Name: Tesla T4


In [4]:
#using empty

a = torch.empty(2,3)

# The empty function create the space in the memory and the result is noting but it is already stored 
#value in the space 

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
#using Zero

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using Rand

torch.rand(2,3)

tensor([[0.3703, 0.1769, 0.4885],
        [0.2009, 0.4466, 0.6401]])

In [9]:
#by manual seed 

torch.manual_seed(90)
torch.rand(2,3)

tensor([[0.1819, 0.7287, 0.3675],
        [0.6684, 0.2857, 0.3219]])

In [10]:
#by manual seed 

torch.manual_seed(90)
torch.rand(2,3)

tensor([[0.1819, 0.7287, 0.3675],
        [0.6684, 0.2857, 0.3219]])

In [11]:
#create a custom tensor

b = torch.tensor([[1,2,3],[4,5,6]])
print(b)
type(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Tensor

In [12]:
torch.arange(1,100,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [13]:
torch.linspace(0,10,2)

'''
    torch.linspace is a function in the PyTorch library that creates a one-dimensional array (tensor) of evenly 
    spaced numbers between a start and an end value.

    torch.linspace(start, end, steps)

    torch.linspace(start, end, steps)
    start: The beginning number of the sequence.
    end: The final number of the sequence.
    steps: The total number of values to generate.
    For instance, torch.linspace(0, 10, 5) will give you:
    tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
    This means it creates 5 numbers evenly spaced between 0 and 10.

'''

'\n    torch.linspace is a function in the PyTorch library that creates a one-dimensional array (tensor) of evenly \n    spaced numbers between a start and an end value.\n\n    torch.linspace(start, end, steps)\n\n    torch.linspace(start, end, steps)\n    start: The beginning number of the sequence.\n    end: The final number of the sequence.\n    steps: The total number of values to generate.\n    For instance, torch.linspace(0, 10, 5) will give you:\n    tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])\n    This means it creates 5 numbers evenly spaced between 0 and 10.\n\n'

In [14]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [16]:
#shape
s = torch.full((3,3),5)
s.shape

torch.Size([3, 3])

In [17]:
# tensor like s 

torch.empty_like(s)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(s)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [19]:
#type
s.dtype

torch.int64

In [20]:
p = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.int32)

In [21]:
torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
p.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
torch.rand_like(p, dtype=torch.float32)

tensor([[0.5514, 0.9196, 0.6360],
        [0.2115, 0.5336, 0.8606]])

In [24]:
p + 2
p-2
p*2
(p*100)//2
((p*100)//2)%2
p**2

tensor([[ 1,  4,  9],
        [16, 25, 36]], dtype=torch.int32)

In [25]:
q= torch.tensor([[10,11,13],[56,78,54]])
q

tensor([[10, 11, 13],
        [56, 78, 54]])

In [26]:
p+q
p*q
p**q

tensor([[                   1,                 2048,              1594323],
        [                   0, -3617894824729806615, -6467169064904032256]])

In [27]:
c = torch.tensor([-1,-2,3,-4])
c

tensor([-1, -2,  3, -4])

In [28]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
torch.neg(c)

tensor([ 1,  2, -3,  4])

In [30]:
d = torch.tensor([1.9, 2.3, 3.7, 4.1])

In [31]:
torch.round(d)
torch.ceil(d)
torch.floor(d)

tensor([1., 2., 3., 4.])

In [32]:
torch.clamp(d, min = 2, max = 5)

tensor([2.0000, 2.3000, 3.7000, 4.1000])

In [33]:
e = torch.randint(size=(2,3), low = 0, high = 10)
e

tensor([[5, 5, 2],
        [8, 4, 7]])

In [34]:
#sum 
p= torch.sum(e)
print(p)
#sum along column
q = torch.sum(e, dim = 0)
print(q)
# sum along row
r= torch.sum(e, dim = 1)
print(r)


tensor(31)
tensor([13,  9,  9])
tensor([12, 19])


In [35]:
e = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[4., 7., 0.],
        [6., 2., 3.]])

In [36]:
torch.mean(e)
torch.mean(e, dim = 0)
torch.mean(e, dim = 1)

tensor([3.6667, 3.6667])

In [37]:
torch.max(e)
torch.min(e)

tensor(0.)

In [38]:
torch.prod(e)

tensor(0.)

In [39]:
torch.std(e)

tensor(2.5820)

In [40]:
torch.var(e)

tensor(6.6667)

In [41]:
torch.argmax(e)

tensor(1)

In [42]:
torch.argmin(e)

tensor(2)

In [43]:
f=  torch.randint(size=(2,3), low = 0, high = 10)
g=  torch.randint(size=(3,2), low = 0, high = 10)
print(f)
print(g)

tensor([[6, 4, 5],
        [8, 4, 0]])
tensor([[3, 0],
        [6, 7],
        [0, 5]])


In [44]:
# matrix multiplication

torch.matmul(f,g)

tensor([[42, 53],
        [48, 28]])

In [45]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [46]:
f

tensor([[6, 4, 5],
        [8, 4, 0]])

In [47]:
torch.transpose(f, 0, 1)

tensor([[6, 8],
        [4, 4],
        [5, 0]])

In [48]:
i=  torch.randint(size=(2,3), low = 0, high = 10)
j=  torch.randint(size=(2,3), low = 0, high = 10)
print(i)
print(j)

tensor([[8, 5, 0],
        [5, 6, 4]])
tensor([[1, 0, 5],
        [1, 2, 8]])


In [49]:
# comparision
i == j
i>j
i<j
i=j

In [50]:
k =  torch.randint(size=(2,3), low = 0, high = 10)

In [51]:
torch.log(k)

tensor([[2.0794,   -inf, 1.3863],
        [  -inf, 1.9459, 1.0986]])

In [52]:
torch.exp(k)

tensor([[2.9810e+03, 1.0000e+00, 5.4598e+01],
        [1.0000e+00, 1.0966e+03, 2.0086e+01]])

In [53]:
torch.sqrt(k)

tensor([[2.8284, 0.0000, 2.0000],
        [0.0000, 2.6458, 1.7321]])

In [54]:
k =  torch.randint(size=(2,3), low = 0, high = 10 , dtype = torch.float32)
print(k)

tensor([[8., 0., 3.],
        [2., 0., 4.]])


In [55]:
torch.sigmoid(k)

tensor([[0.9997, 0.5000, 0.9526],
        [0.8808, 0.5000, 0.9820]])

In [56]:
torch.softmax(k, dim =0 )

tensor([[0.9975, 0.5000, 0.2689],
        [0.0025, 0.5000, 0.7311]])

In [57]:
torch.relu(k)

tensor([[8., 0., 3.],
        [2., 0., 4.]])

In [58]:
m= torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.6096, 0.1980, 0.5490],
        [0.4538, 0.4030, 0.5792]])
tensor([[0.4877, 0.6355, 0.7135],
        [0.4212, 0.7627, 0.1834]])


In [59]:
m.add_(n)

tensor([[1.0974, 0.8335, 1.2625],
        [0.8750, 1.1658, 0.7626]])

In [60]:
m

tensor([[1.0974, 0.8335, 1.2625],
        [0.8750, 1.1658, 0.7626]])

In [61]:
n

tensor([[0.4877, 0.6355, 0.7135],
        [0.4212, 0.7627, 0.1834]])

In [62]:
m.relu_()

tensor([[1.0974, 0.8335, 1.2625],
        [0.8750, 1.1658, 0.7626]])

In [63]:
m

tensor([[1.0974, 0.8335, 1.2625],
        [0.8750, 1.1658, 0.7626]])

Copy a Tensor****

In [64]:
a = torch.rand(size=(2,3), dtype = torch.float64)
print(a)

tensor([[0.7645, 0.9064, 0.5898],
        [0.9699, 0.3019, 0.7634]], dtype=torch.float64)


In [65]:
b = a

In [66]:
b

tensor([[0.7645, 0.9064, 0.5898],
        [0.9699, 0.3019, 0.7634]], dtype=torch.float64)

In [67]:
a[0][0] = 0

In [68]:
a

tensor([[0.0000, 0.9064, 0.5898],
        [0.9699, 0.3019, 0.7634]], dtype=torch.float64)

In [69]:
b

tensor([[0.0000, 0.9064, 0.5898],
        [0.9699, 0.3019, 0.7634]], dtype=torch.float64)

In [70]:
b = a.clone()

In [71]:
b

tensor([[0.0000, 0.9064, 0.5898],
        [0.9699, 0.3019, 0.7634]], dtype=torch.float64)

In [72]:
b[0][0] = 10

In [73]:
b

tensor([[10.0000,  0.9064,  0.5898],
        [ 0.9699,  0.3019,  0.7634]], dtype=torch.float64)

In [74]:
a

tensor([[0.0000, 0.9064, 0.5898],
        [0.9699, 0.3019, 0.7634]], dtype=torch.float64)

In [ ]:
id(a)
