In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
import torch
device = torch.device('cuda')

In [5]:
torch.rand((2,3), device= device)


tensor([[0.1289, 0.9437, 0.2650],
        [0.4512, 0.0694, 0.7761]], device='cuda:0')

In [7]:
#move Existing Tensor on GPU

a = torch.rand(2,3)
print(a)


tensor([[0.6523, 0.9508, 0.9676],
        [0.9619, 0.5551, 0.5224]])


In [9]:
b = a.to(device)

print(b+5)

tensor([[5.6523, 5.9508, 5.9676],
        [5.9619, 5.5551, 5.5224]], device='cuda:0')


In [12]:
import torch 
import time
size = 10000

mat1 = torch.randn(size, size)
mat2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(mat1,mat2)
cpu_time = time.time()-start_time
print(f"cpu time {cpu_time}")

mat1_gpu = mat1.to(device)
mat2_gpu = mat2.to(device)
start_time = time.time()
result_cpu = torch.matmul(mat1_gpu,mat2_gpu)
gpu_time = time.time()-start_time
print(f"gpu time {gpu_time}")

cpu time 7.028382062911987
gpu time 0.039106130599975586
