In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/data-for-breast-cancer/data.csv


In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("/kaggle/input/data-for-breast-cancer/data.csv")
print(df.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
df.drop(columns = ['Unnamed: 32', 'id'], inplace = True)


In [6]:
print(df.columns)

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')


In [7]:
print(df.head())

  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33 

In [8]:
x_train, x_test, y_train , y_test= train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [9]:
print(y_train.name)

diagnosis


In [10]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [11]:
x_train

array([[-1.12348728e-01, -8.24932207e-01, -1.59900229e-01, ...,
        -1.22525333e+00, -1.64269502e+00, -8.55134982e-01],
       [ 3.65837540e-01,  1.39351967e-01,  4.09430347e-01, ...,
         1.46210661e+00,  5.13006614e-01,  9.99745461e-01],
       [ 4.38544224e-01,  2.03945165e-01,  4.17546250e-01, ...,
         4.98152487e-01,  1.82136167e+00,  1.24669700e+00],
       ...,
       [-7.21966310e-01, -2.32058923e-01, -7.47897382e-01, ...,
        -4.78113818e-01,  5.50341808e-01, -2.77268382e-01],
       [-8.53397623e-01,  7.09156251e-01, -8.44882419e-01, ...,
        -7.59642474e-01,  4.83787766e-01, -1.84524360e-01],
       [-1.01163085e-01,  1.18207074e+00,  7.94644982e-04, ...,
         5.61214906e-01,  1.26620357e+00,  1.89974662e+00]])

In [12]:
x_test

array([[-0.86806631, -0.97463924, -0.84176548, ..., -0.10739863,
         0.45962569,  0.33578575],
       [ 0.59094815,  1.20216197,  0.57655265, ..., -0.03624496,
        -0.34412456, -1.28036527],
       [-0.070025  , -0.64291314, -0.12534089, ..., -0.43826318,
        -0.34902548, -0.41529338],
       ...,
       [-1.26952373, -0.80272279, -1.28165986, ..., -1.01153534,
        -0.29184812, -0.18788653],
       [-1.23754116, -0.80030143, -1.21560966, ..., -0.79015041,
        -0.84565165,  0.41043075],
       [-0.28324214,  0.0883371 , -0.26800934, ..., -0.25164652,
         0.94154911,  0.38554908]])

In [13]:
from sklearn.preprocessing import LabelEncoder


In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [15]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,

In [16]:
y_test

array([0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0])

In [17]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)
print(x_train_tensor)

tensor([[-1.1235e-01, -8.2493e-01, -1.5990e-01,  ..., -1.2253e+00,
         -1.6427e+00, -8.5513e-01],
        [ 3.6584e-01,  1.3935e-01,  4.0943e-01,  ...,  1.4621e+00,
          5.1301e-01,  9.9975e-01],
        [ 4.3854e-01,  2.0395e-01,  4.1755e-01,  ...,  4.9815e-01,
          1.8214e+00,  1.2467e+00],
        ...,
        [-7.2197e-01, -2.3206e-01, -7.4790e-01,  ..., -4.7811e-01,
          5.5034e-01, -2.7727e-01],
        [-8.5340e-01,  7.0916e-01, -8.4488e-01,  ..., -7.5964e-01,
          4.8379e-01, -1.8452e-01],
        [-1.0116e-01,  1.1821e+00,  7.9464e-04,  ...,  5.6121e-01,
          1.2662e+00,  1.8997e+00]], dtype=torch.float64)


In [33]:
class mySimpleNN():

    def __init__(self, x):
        
        self.weight = torch.rand(x.shape[1], 1 ,dtype = torch.float64, requires_grad = True)
        self.bais = torch.zeros(1, dtype = torch.float64, requires_grad = True)
        
    def forward(self, x):
        z = torch.matmul(x,  self.weight) + self.bais
        y_pred = torch.sigmoid(z)
        return y_pred
    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        predection = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-predection)).mean()
        return loss

In [34]:
learning_rate = 0.1
epochs = 25

In [36]:
#create model
model = mySimpleNN(x_train_tensor)
for epoch in range(epochs):
    #forword pass
    y_pred = model.forward(x_train_tensor)
    loss = model.loss_function(y_pred,y_train_tensor)
    loss.backward()
    with torch.no_grad():
        model.weight -= learning_rate*model.weight.grad
        model.bais -= learning_rate* model.bais.grad
    model.weight.grad.zero_()
    model.bais.grad.zero_()
    print(f'epoch : {epoch+1}, loss : {loss.item()}')

epoch : 1, loss : 3.778525312442904
epoch : 2, loss : 3.649435676306772
epoch : 3, loss : 3.5201568071133487
epoch : 4, loss : 3.386066447085646
epoch : 5, loss : 3.2441563609588875
epoch : 6, loss : 3.0891393977473505
epoch : 7, loss : 2.929456747634925
epoch : 8, loss : 2.765431663642711
epoch : 9, loss : 2.595930615098237
epoch : 10, loss : 2.416176998538869
epoch : 11, loss : 2.2353432213327893
epoch : 12, loss : 2.059725222281125
epoch : 13, loss : 1.8905061884423102
epoch : 14, loss : 1.7285290967294156
epoch : 15, loss : 1.5699167081366086
epoch : 16, loss : 1.4124191828990122
epoch : 17, loss : 1.2700149711369741
epoch : 18, loss : 1.145175864321748
epoch : 19, loss : 1.0399059649780273
epoch : 20, loss : 0.9551822718462525
epoch : 21, loss : 0.8904186024925738
epoch : 22, loss : 0.843286437338684
epoch : 23, loss : 0.8101924520053767
epoch : 24, loss : 0.7872414239637443
epoch : 25, loss : 0.7710915990735765


In [38]:
print(model.weight)

tensor([[ 0.2295],
        [-0.0149],
        [ 0.3442],
        [ 0.1745],
        [ 0.3660],
        [-0.4548],
        [-0.0987],
        [-0.2567],
        [ 0.0555],
        [ 0.0146],
        [ 0.3333],
        [ 0.0396],
        [ 0.0662],
        [-0.4093],
        [ 0.1015],
        [ 0.2080],
        [ 0.1187],
        [ 0.2424],
        [ 0.4923],
        [-0.1623],
        [-0.5010],
        [ 0.0458],
        [ 0.1800],
        [ 0.4303],
        [ 0.2669],
        [-0.3891],
        [ 0.1741],
        [-0.3471],
        [-0.0906],
        [ 0.1237]], dtype=torch.float64, requires_grad=True)


In [42]:
with torch.no_grad():
    y_pred = model.forward(x_train_tensor)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(accuracy)
print(y_pred)

tensor(0.5275)
tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
     