In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch
import torch.nn as nn

In [8]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, feature):
        out = self.linear(feature)
        out = self.sigmoid(out)
        return out
        

In [10]:
feature = torch.rand(10,5)
print(feature)
model = Model(feature.shape[1])
#print(feature.shape[1])
model(feature)

tensor([[0.8526, 0.5458, 0.2647, 0.6146, 0.0055],
        [0.4687, 0.9485, 0.3904, 0.4202, 0.3795],
        [0.9872, 0.0206, 0.3763, 0.5453, 0.8176],
        [0.2704, 0.1852, 0.4483, 0.3757, 0.7450],
        [0.2913, 0.5939, 0.4606, 0.0788, 0.1573],
        [0.8975, 0.8971, 0.2058, 0.8221, 0.8452],
        [0.3810, 0.5038, 0.3666, 0.8855, 0.3150],
        [0.9463, 0.9794, 0.0046, 0.7431, 0.3772],
        [0.7959, 0.0458, 0.6583, 0.2862, 0.7062],
        [0.9579, 0.8204, 0.7327, 0.3012, 0.9661]])


tensor([[0.4059],
        [0.4299],
        [0.3249],
        [0.3758],
        [0.3864],
        [0.4296],
        [0.4590],
        [0.4479],
        [0.3046],
        [0.3320]], grad_fn=<SigmoidBackward0>)

In [15]:
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.3624,  0.2916, -0.2498,  0.4347, -0.1114]], requires_grad=True)
Parameter containing:
tensor([-0.4316], requires_grad=True)


In [16]:
from torchinfo import summary
summary(model, size = (10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [21]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, feature):
        out = self.linear1(feature)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [22]:
feature = torch.rand(10,5)
print(feature)
model = Model(feature.shape[1])
#print(feature.shape[1])
model(feature)

tensor([[0.8859, 0.0829, 0.9698, 0.6411, 0.5211],
        [0.2884, 0.6312, 0.5764, 0.8584, 0.8332],
        [0.0422, 0.8540, 0.6950, 0.7428, 0.1844],
        [0.1887, 0.2659, 0.5495, 0.4016, 0.1498],
        [0.1042, 0.0664, 0.0284, 0.9871, 0.8104],
        [0.4882, 0.1831, 0.9879, 0.9891, 0.2201],
        [0.1350, 0.7392, 0.0573, 0.6217, 0.6682],
        [0.1797, 0.7991, 0.9216, 0.6974, 0.2326],
        [0.9639, 0.0972, 0.5665, 0.4615, 0.4920],
        [0.2021, 0.3185, 0.4574, 0.7027, 0.1909]])


tensor([[0.4299],
        [0.4373],
        [0.4401],
        [0.4375],
        [0.4490],
        [0.4395],
        [0.4301],
        [0.4363],
        [0.4306],
        [0.4420]], grad_fn=<SigmoidBackward0>)

In [24]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2051, -0.2167, -0.3960,  0.2935,  0.3598],
        [-0.2365, -0.0915, -0.2070,  0.3729, -0.2155],
        [ 0.0691,  0.3459, -0.1628, -0.2530,  0.2788]], requires_grad=True)

In [25]:
from torchinfo import summary
summary(model, size = (10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [27]:
# sequential 

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )


    def forward(self, features):
        out = self.network(features)
        return out

In [28]:
feature = torch.rand(10,5)
print(feature)
model = Model(feature.shape[1])
#print(feature.shape[1])
model(feature)

tensor([[0.9156, 0.2137, 0.1213, 0.3998, 0.2299],
        [0.9737, 0.8401, 0.1908, 0.3382, 0.7702],
        [0.4282, 0.5800, 0.3543, 0.4541, 0.8973],
        [0.1478, 0.2278, 0.8697, 0.8469, 0.2487],
        [0.1686, 0.9144, 0.5432, 0.0033, 0.1887],
        [0.9017, 0.9233, 0.9326, 0.0477, 0.8634],
        [0.6673, 0.8620, 0.6538, 0.9865, 0.4994],
        [0.7497, 0.3628, 0.5663, 0.3467, 0.5880],
        [0.1216, 0.2499, 0.1265, 0.1566, 0.8357],
        [0.5500, 0.6678, 0.9438, 0.7113, 0.9284]])


tensor([[0.6074],
        [0.6074],
        [0.6139],
        [0.6267],
        [0.6093],
        [0.6102],
        [0.6189],
        [0.6080],
        [0.6099],
        [0.6231]], grad_fn=<SigmoidBackward0>)

In [29]:
from torchinfo import summary
summary(model, size = (10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       18
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 22
Trainable params: 22
Non-trainable params: 0