In [77]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/data-for-breast-cancer/data.csv


In [78]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [79]:
df = pd.read_csv("/kaggle/input/data-for-breast-cancer/data.csv")
print(df.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


In [80]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [81]:
df.drop(columns = ['Unnamed: 32', 'id'], inplace = True)


In [82]:
print(df.columns)

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')


In [83]:
print(df.head())

  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33 

In [84]:
x_train, x_test, y_train , y_test= train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

In [85]:
print(y_train.name)

diagnosis


In [86]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [87]:
x_train

array([[-0.01682744, -0.82977709, -0.08362914, ..., -0.47121766,
        -1.22793951, -0.96092255],
       [ 1.85331564,  0.48476279,  1.90685622, ...,  1.50445609,
        -0.6574118 ,  0.3868438 ],
       [ 0.25358899, -0.52587809,  0.19010904, ..., -0.43006416,
        -0.78345862, -1.12696453],
       ...,
       [-0.50073052, -1.60012573, -0.52706023, ..., -0.29145797,
        -0.08190856, -0.92500566],
       [ 0.1738873 , -1.22555254,  0.27268467, ..., -0.03306297,
        -0.08190856,  0.50990328],
       [-1.80755348,  1.48598045, -1.80161495, ..., -1.72815861,
         0.30120743,  0.93972829]])

In [88]:
x_test

array([[-1.25326416, -0.54711662, -1.245578  , ..., -0.98196134,
        -0.01352946, -0.56566218],
       [-1.03496526,  1.22949316, -1.03743643, ..., -0.89954473,
         0.61661676, -0.21133108],
       [-0.40883665, -0.78399792, -0.44981477, ..., -0.95308545,
         0.90918465, -0.71256869],
       ...,
       [ 1.39621881,  1.50883432,  1.41160054, ...,  0.86218549,
         1.01120833,  1.21292288],
       [ 0.87444497,  1.30547396,  0.86364436, ..., -0.16952608,
        -2.09301198, -0.8252894 ],
       [-1.41712935, -1.30022038, -1.36661906, ..., -0.73019966,
         1.02471146,  0.17441399]])

In [89]:
from sklearn.preprocessing import LabelEncoder


In [90]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [91]:
y_train

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,

In [92]:
y_test

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0])

In [93]:
import torch

# Convert NumPy arrays to PyTorch tensors
x_train_tensor = torch.from_numpy(x_train).to(torch.float32)
x_test_tensor = torch.from_numpy(x_test).to(torch.float32)
y_train_tensor = torch.from_numpy(y_train).to(torch.float32)
y_test_tensor = torch.from_numpy(y_test).to(torch.float32)

# Verify dtype
print(x_train_tensor.dtype)  # Should print torch.float32
print(y_train_tensor.dtype)  # Should print torch.float32


torch.float32
torch.float32


In [95]:
import torch
import torch.nn as nn

class mySimpleNN(nn.Module):
    def __init__(self, number_features):
        super().__init__()
        self.linear = nn.Linear(number_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features)
        y_pred = self.sigmoid(out)
        return y_pred


In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
loss_function = nn.BCELoss()

In [97]:
#create model
model = mySimpleNN(x_train_tensor.shape[1])
print(x_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
for epoch in range(epochs):
    #forword pass
    y_pred = model(x_train_tensor)
    loss = loss_function(y_pred,y_train_tensor.view(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'epoch : {epoch+1}, loss:{loss.item()}')

30
epoch : 1, loss:0.8129256367683411
epoch : 2, loss:0.5966998934745789
epoch : 3, loss:0.48438623547554016
epoch : 4, loss:0.4174886643886566
epoch : 5, loss:0.3725436329841614
epoch : 6, loss:0.3399283289909363
epoch : 7, loss:0.31497395038604736
epoch : 8, loss:0.2951315641403198
epoch : 9, loss:0.27888694405555725
epoch : 10, loss:0.2652812600135803
epoch : 11, loss:0.2536764144897461
epoch : 12, loss:0.24363009631633759
epoch : 13, loss:0.2348252236843109
epoch : 14, loss:0.2270282357931137
epoch : 15, loss:0.2200627326965332
epoch : 16, loss:0.21379287540912628
epoch : 17, loss:0.20811206102371216
epoch : 18, loss:0.20293529331684113
epoch : 19, loss:0.19819386303424835
epoch : 20, loss:0.19383157789707184
epoch : 21, loss:0.18980184197425842
epoch : 22, loss:0.18606579303741455
epoch : 23, loss:0.18259046971797943
epoch : 24, loss:0.17934802174568176
epoch : 25, loss:0.17631438374519348


In [98]:
print(model.linear.weight)

Parameter containing:
tensor([[ 0.3150,  0.2721,  0.3457,  0.1773,  0.0643,  0.1415,  0.1801,  0.3123,
          0.1485, -0.0985,  0.1583,  0.0964,  0.2066,  0.2112, -0.1301, -0.0723,
          0.1307, -0.0938,  0.0671, -0.1083,  0.1864,  0.1364,  0.2411,  0.2924,
          0.3060,  0.0259,  0.1455,  0.1179,  0.1679,  0.2202]],
       requires_grad=True)


In [99]:
with torch.no_grad():
    y_pred = model.forward(x_train_tensor)
    y_pred = (y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(accuracy)


tensor(0.5241)
